spring:
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://localhost:3306/Activiti_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true